### ISSUE TITLE
Team 126 - The Kermits: Peer-to-peer code review

### ISSUE THREAD

**Issue by Joseph-Burke** [m15e/embedding-images-and-video#2]
Border radius causes rounding of input search box. Would be better if there wasn't an inward dip at the meeting of the button and the search bar.

h tags help search engine optimization so the video titles might have been better as p tags.

align-items in the navbar would have had all the elements in the navbar sit on the same horizontal line.

CSS selectors can be done either by giving id and class attributes to the elements we want to select, or by identifying via the semantic HTML tags (e.g. header ul li {<code>}). Which is better depends on that situation, but focus on readability.

Nice, modular code in the HTML file makes it clean and readable.

**Comment by m15e** [comment]
issues resolved
